/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QMP->QAPI command dispatch
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#include "qemu-objects.h"
#include "qapi/qmp-core.h"
#include "qapi/qapi-visit-core.h"
#include "qapi/qmp-output-visitor.h"
#include "qapi/qmp-input-visitor.h"
#include "qapi/qapi-dealloc-visitor.h"
#include "qapi-types.h"
#include "qapi-visit.h"

#include "qmp-commands.h"

void qmp_marshal_output_query_name(NameInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_NameInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_NameInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_name(QDict *args, QObject **ret, Error **errp)
{
    NameInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_name(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_name(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_version(VersionInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_VersionInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_VersionInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_version(QDict *args, QObject **ret, Error **errp)
{
    VersionInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_version(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_version(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_kvm(KvmInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_KvmInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_KvmInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_kvm(QDict *args, QObject **ret, Error **errp)
{
    KvmInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_kvm(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_kvm(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_status(StatusInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_StatusInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_StatusInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_status(QDict *args, QObject **ret, Error **errp)
{
    StatusInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_status(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_status(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_uuid(UuidInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_UuidInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_UuidInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_uuid(QDict *args, QObject **ret, Error **errp)
{
    UuidInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_uuid(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_uuid(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_chardev(ChardevInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_ChardevInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_ChardevInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_chardev(QDict *args, QObject **ret, Error **errp)
{
    ChardevInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_chardev(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_chardev(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_commands(CommandInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_CommandInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_CommandInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_commands(QDict *args, QObject **ret, Error **errp)
{
    CommandInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_commands(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_commands(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_migrate(MigrationInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_MigrationInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_MigrationInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_migrate(QDict *args, QObject **ret, Error **errp)
{
    MigrationInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_migrate(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_migrate(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_mice(MouseInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_MouseInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_MouseInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_mice(QDict *args, QObject **ret, Error **errp)
{
    MouseInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_mice(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_mice(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_cpus(CpuInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_CpuInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_CpuInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_cpus(QDict *args, QObject **ret, Error **errp)
{
    CpuInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_cpus(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_cpus(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_block(BlockInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_BlockInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_BlockInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_block(QDict *args, QObject **ret, Error **errp)
{
    BlockInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_block(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_block(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_blockstats(BlockStatsList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_BlockStatsList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_BlockStatsList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_blockstats(QDict *args, QObject **ret, Error **errp)
{
    BlockStatsList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_blockstats(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_blockstats(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_vnc(VncInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_VncInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_VncInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_vnc(QDict *args, QObject **ret, Error **errp)
{
    VncInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_vnc(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_vnc(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_spice(SpiceInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_SpiceInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_SpiceInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_spice(QDict *args, QObject **ret, Error **errp)
{
    SpiceInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_spice(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_spice(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_balloon(BalloonInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_BalloonInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_BalloonInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_balloon(QDict *args, QObject **ret, Error **errp)
{
    BalloonInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_balloon(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_balloon(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_pci(PciInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_PciInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_PciInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_pci(QDict *args, QObject **ret, Error **errp)
{
    PciInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_pci(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_pci(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_output_query_block_jobs(BlockJobInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_BlockJobInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_BlockJobInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_block_jobs(QDict *args, QObject **ret, Error **errp)
{
    BlockJobInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_block_jobs(errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_query_block_jobs(retval, ret, errp);
    }

out:

    return;
}

void qmp_marshal_input_quit(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_quit(errp);

out:

    return;
}

void qmp_marshal_input_stop(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_stop(errp);

out:

    return;
}

void qmp_marshal_input_system_reset(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_system_reset(errp);

out:

    return;
}

void qmp_marshal_input_system_powerdown(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_system_powerdown(errp);

out:

    return;
}

void qmp_marshal_input_cpu(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    int64_t index;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_int(v, &index, "index", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_cpu(index, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_int(v, &index, "index", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_memsave(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    int64_t val;
    int64_t size;
    char * filename = NULL;
    bool has_cpu_index = false;
    int64_t cpu_index;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_int(v, &val, "val", errp);
    visit_type_int(v, &size, "size", errp);
    visit_type_str(v, &filename, "filename", errp);
    visit_start_optional(v, &has_cpu_index, "cpu-index", errp);
    if (has_cpu_index) {
        visit_type_int(v, &cpu_index, "cpu-index", errp);
    }
    visit_end_optional(v, errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_memsave(val, size, filename, has_cpu_index, cpu_index, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_int(v, &val, "val", errp);
    visit_type_int(v, &size, "size", errp);
    visit_type_str(v, &filename, "filename", errp);
    visit_start_optional(v, &has_cpu_index, "cpu-index", errp);
    if (has_cpu_index) {
        visit_type_int(v, &cpu_index, "cpu-index", errp);
    }
    visit_end_optional(v, errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_pmemsave(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    int64_t val;
    int64_t size;
    char * filename = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_int(v, &val, "val", errp);
    visit_type_int(v, &size, "size", errp);
    visit_type_str(v, &filename, "filename", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_pmemsave(val, size, filename, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_int(v, &val, "val", errp);
    visit_type_int(v, &size, "size", errp);
    visit_type_str(v, &filename, "filename", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_cont(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_cont(errp);

out:

    return;
}

void qmp_marshal_input_inject_nmi(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_inject_nmi(errp);

out:

    return;
}

void qmp_marshal_input_set_link(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * name = NULL;
    bool up;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &name, "name", errp);
    visit_type_bool(v, &up, "up", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_set_link(name, up, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &name, "name", errp);
    visit_type_bool(v, &up, "up", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_block_passwd(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;
    char * password = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    visit_type_str(v, &password, "password", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_block_passwd(device, password, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    visit_type_str(v, &password, "password", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_balloon(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    int64_t value;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_int(v, &value, "value", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_balloon(value, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_int(v, &value, "value", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_block_resize(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;
    int64_t size;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    visit_type_int(v, &size, "size", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_block_resize(device, size, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    visit_type_int(v, &size, "size", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_blockdev_snapshot_sync(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;
    char * snapshot_file = NULL;
    bool has_format = false;
    char * format = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    visit_type_str(v, &snapshot_file, "snapshot-file", errp);
    visit_start_optional(v, &has_format, "format", errp);
    if (has_format) {
        visit_type_str(v, &format, "format", errp);
    }
    visit_end_optional(v, errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_blockdev_snapshot_sync(device, snapshot_file, has_format, format, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    visit_type_str(v, &snapshot_file, "snapshot-file", errp);
    visit_start_optional(v, &has_format, "format", errp);
    if (has_format) {
        visit_type_str(v, &format, "format", errp);
    }
    visit_end_optional(v, errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_output_human_monitor_command(char * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_str(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_human_monitor_command(QDict *args, QObject **ret, Error **errp)
{
    char * retval = NULL;
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * command_line = NULL;
    bool has_cpu_index = false;
    int64_t cpu_index;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &command_line, "command-line", errp);
    visit_start_optional(v, &has_cpu_index, "cpu-index", errp);
    if (has_cpu_index) {
        visit_type_int(v, &cpu_index, "cpu-index", errp);
    }
    visit_end_optional(v, errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_human_monitor_command(command_line, has_cpu_index, cpu_index, errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_human_monitor_command(retval, ret, errp);
    }

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &command_line, "command-line", errp);
    visit_start_optional(v, &has_cpu_index, "cpu-index", errp);
    if (has_cpu_index) {
        visit_type_int(v, &cpu_index, "cpu-index", errp);
    }
    visit_end_optional(v, errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_migrate_cancel(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_migrate_cancel(errp);

out:

    return;
}

void qmp_marshal_input_migrate_set_downtime(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    double value;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_number(v, &value, "value", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_migrate_set_downtime(value, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_number(v, &value, "value", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_migrate_set_speed(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    int64_t value;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_int(v, &value, "value", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_migrate_set_speed(value, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_int(v, &value, "value", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_output_qom_list(DevicePropertyInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_DevicePropertyInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_DevicePropertyInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_qom_list(QDict *args, QObject **ret, Error **errp)
{
    DevicePropertyInfoList * retval = NULL;
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * path = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &path, "path", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_qom_list(path, errp);
    if (!error_is_set(errp)) {
        qmp_marshal_output_qom_list(retval, ret, errp);
    }

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &path, "path", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_set_password(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * protocol = NULL;
    char * password = NULL;
    bool has_connected = false;
    char * connected = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &protocol, "protocol", errp);
    visit_type_str(v, &password, "password", errp);
    visit_start_optional(v, &has_connected, "connected", errp);
    if (has_connected) {
        visit_type_str(v, &connected, "connected", errp);
    }
    visit_end_optional(v, errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_set_password(protocol, password, has_connected, connected, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &protocol, "protocol", errp);
    visit_type_str(v, &password, "password", errp);
    visit_start_optional(v, &has_connected, "connected", errp);
    if (has_connected) {
        visit_type_str(v, &connected, "connected", errp);
    }
    visit_end_optional(v, errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_expire_password(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * protocol = NULL;
    char * time = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &protocol, "protocol", errp);
    visit_type_str(v, &time, "time", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_expire_password(protocol, time, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &protocol, "protocol", errp);
    visit_type_str(v, &time, "time", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_eject(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;
    bool has_force = false;
    bool force;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    visit_start_optional(v, &has_force, "force", errp);
    if (has_force) {
        visit_type_bool(v, &force, "force", errp);
    }
    visit_end_optional(v, errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_eject(device, has_force, force, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    visit_start_optional(v, &has_force, "force", errp);
    if (has_force) {
        visit_type_bool(v, &force, "force", errp);
    }
    visit_end_optional(v, errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_change_vnc_password(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * password = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &password, "password", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_change_vnc_password(password, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &password, "password", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_change(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;
    char * target = NULL;
    bool has_arg = false;
    char * arg = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    visit_type_str(v, &target, "target", errp);
    visit_start_optional(v, &has_arg, "arg", errp);
    if (has_arg) {
        visit_type_str(v, &arg, "arg", errp);
    }
    visit_end_optional(v, errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_change(device, target, has_arg, arg, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    visit_type_str(v, &target, "target", errp);
    visit_start_optional(v, &has_arg, "arg", errp);
    if (has_arg) {
        visit_type_str(v, &arg, "arg", errp);
    }
    visit_end_optional(v, errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_block_set_io_throttle(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;
    int64_t bps;
    int64_t bps_rd;
    int64_t bps_wr;
    int64_t iops;
    int64_t iops_rd;
    int64_t iops_wr;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    visit_type_int(v, &bps, "bps", errp);
    visit_type_int(v, &bps_rd, "bps_rd", errp);
    visit_type_int(v, &bps_wr, "bps_wr", errp);
    visit_type_int(v, &iops, "iops", errp);
    visit_type_int(v, &iops_rd, "iops_rd", errp);
    visit_type_int(v, &iops_wr, "iops_wr", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_block_set_io_throttle(device, bps, bps_rd, bps_wr, iops, iops_rd, iops_wr, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    visit_type_int(v, &bps, "bps", errp);
    visit_type_int(v, &bps_rd, "bps_rd", errp);
    visit_type_int(v, &bps_wr, "bps_wr", errp);
    visit_type_int(v, &iops, "iops", errp);
    visit_type_int(v, &iops_rd, "iops_rd", errp);
    visit_type_int(v, &iops_wr, "iops_wr", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_block_stream(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;
    bool has_base = false;
    char * base = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    visit_start_optional(v, &has_base, "base", errp);
    if (has_base) {
        visit_type_str(v, &base, "base", errp);
    }
    visit_end_optional(v, errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_block_stream(device, has_base, base, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    visit_start_optional(v, &has_base, "base", errp);
    if (has_base) {
        visit_type_str(v, &base, "base", errp);
    }
    visit_end_optional(v, errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_block_job_set_speed(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;
    int64_t value;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    visit_type_int(v, &value, "value", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_block_job_set_speed(device, value, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    visit_type_int(v, &value, "value", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

void qmp_marshal_input_block_job_cancel(QDict *args, QObject **ret, Error **errp)
{
    QmpInputVisitor *mi;
    QapiDeallocVisitor *md;
    Visitor *v;
    char * device = NULL;

    mi = qmp_input_visitor_new(QOBJECT(args));
    v = qmp_input_get_visitor(mi);
    visit_type_str(v, &device, "device", errp);
    qmp_input_visitor_cleanup(mi);

    if (error_is_set(errp)) {
        goto out;
    }
    qmp_block_job_cancel(device, errp);

out:
    md = qapi_dealloc_visitor_new();
    v = qapi_dealloc_get_visitor(md);
    visit_type_str(v, &device, "device", errp);
    qapi_dealloc_visitor_cleanup(md);
    return;
}

static void qmp_init_marshal(void)
{
    qmp_register_command("query-name", qmp_marshal_input_query_name);
    qmp_register_command("query-version", qmp_marshal_input_query_version);
    qmp_register_command("query-kvm", qmp_marshal_input_query_kvm);
    qmp_register_command("query-status", qmp_marshal_input_query_status);
    qmp_register_command("query-uuid", qmp_marshal_input_query_uuid);
    qmp_register_command("query-chardev", qmp_marshal_input_query_chardev);
    qmp_register_command("query-commands", qmp_marshal_input_query_commands);
    qmp_register_command("query-migrate", qmp_marshal_input_query_migrate);
    qmp_register_command("query-mice", qmp_marshal_input_query_mice);
    qmp_register_command("query-cpus", qmp_marshal_input_query_cpus);
    qmp_register_command("query-block", qmp_marshal_input_query_block);
    qmp_register_command("query-blockstats", qmp_marshal_input_query_blockstats);
    qmp_register_command("query-vnc", qmp_marshal_input_query_vnc);
    qmp_register_command("query-spice", qmp_marshal_input_query_spice);
    qmp_register_command("query-balloon", qmp_marshal_input_query_balloon);
    qmp_register_command("query-pci", qmp_marshal_input_query_pci);
    qmp_register_command("query-block-jobs", qmp_marshal_input_query_block_jobs);
    qmp_register_command("quit", qmp_marshal_input_quit);
    qmp_register_command("stop", qmp_marshal_input_stop);
    qmp_register_command("system_reset", qmp_marshal_input_system_reset);
    qmp_register_command("system_powerdown", qmp_marshal_input_system_powerdown);
    qmp_register_command("cpu", qmp_marshal_input_cpu);
    qmp_register_command("memsave", qmp_marshal_input_memsave);
    qmp_register_command("pmemsave", qmp_marshal_input_pmemsave);
    qmp_register_command("cont", qmp_marshal_input_cont);
    qmp_register_command("inject-nmi", qmp_marshal_input_inject_nmi);
    qmp_register_command("set_link", qmp_marshal_input_set_link);
    qmp_register_command("block_passwd", qmp_marshal_input_block_passwd);
    qmp_register_command("balloon", qmp_marshal_input_balloon);
    qmp_register_command("block_resize", qmp_marshal_input_block_resize);
    qmp_register_command("blockdev-snapshot-sync", qmp_marshal_input_blockdev_snapshot_sync);
    qmp_register_command("human-monitor-command", qmp_marshal_input_human_monitor_command);
    qmp_register_command("migrate_cancel", qmp_marshal_input_migrate_cancel);
    qmp_register_command("migrate_set_downtime", qmp_marshal_input_migrate_set_downtime);
    qmp_register_command("migrate_set_speed", qmp_marshal_input_migrate_set_speed);
    qmp_register_command("qom-list", qmp_marshal_input_qom_list);
    qmp_register_command("set_password", qmp_marshal_input_set_password);
    qmp_register_command("expire_password", qmp_marshal_input_expire_password);
    qmp_register_command("eject", qmp_marshal_input_eject);
    qmp_register_command("change-vnc-password", qmp_marshal_input_change_vnc_password);
    qmp_register_command("change", qmp_marshal_input_change);
    qmp_register_command("block_set_io_throttle", qmp_marshal_input_block_set_io_throttle);
    qmp_register_command("block_stream", qmp_marshal_input_block_stream);
    qmp_register_command("block_job_set_speed", qmp_marshal_input_block_job_set_speed);
    qmp_register_command("block_job_cancel", qmp_marshal_input_block_job_cancel);
}

qapi_init(qmp_init_marshal);
