/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QMP->QAPI command dispatch
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#include "qemu-objects.h"
#include "qapi/qmp-core.h"
#include "qapi/qapi-visit-core.h"
#include "qapi/qmp-output-visitor.h"
#include "qapi/qmp-input-visitor.h"
#include "qapi/qapi-dealloc-visitor.h"
#include "qapi-types.h"
#include "qapi-visit.h"

#include "qmp-commands.h"

void qmp_marshal_output_query_name(NameInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_NameInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_NameInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_name(QDict *args, QObject **ret, Error **errp)
{
    NameInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_name(errp);
    qmp_marshal_output_query_name(retval, ret, errp);

out:

    return;
}

void qmp_marshal_output_query_version(VersionInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_VersionInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_VersionInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_version(QDict *args, QObject **ret, Error **errp)
{
    VersionInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_version(errp);
    qmp_marshal_output_query_version(retval, ret, errp);

out:

    return;
}

void qmp_marshal_output_query_kvm(KvmInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_KvmInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_KvmInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_kvm(QDict *args, QObject **ret, Error **errp)
{
    KvmInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_kvm(errp);
    qmp_marshal_output_query_kvm(retval, ret, errp);

out:

    return;
}

void qmp_marshal_output_query_status(StatusInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_StatusInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_StatusInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_status(QDict *args, QObject **ret, Error **errp)
{
    StatusInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_status(errp);
    qmp_marshal_output_query_status(retval, ret, errp);

out:

    return;
}

void qmp_marshal_output_query_uuid(UuidInfo * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_UuidInfo(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_UuidInfo(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_uuid(QDict *args, QObject **ret, Error **errp)
{
    UuidInfo * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_uuid(errp);
    qmp_marshal_output_query_uuid(retval, ret, errp);

out:

    return;
}

void qmp_marshal_output_query_chardev(ChardevInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_ChardevInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_ChardevInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_chardev(QDict *args, QObject **ret, Error **errp)
{
    ChardevInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_chardev(errp);
    qmp_marshal_output_query_chardev(retval, ret, errp);

out:

    return;
}

void qmp_marshal_output_query_commands(CommandInfoList * ret_in, QObject **ret_out, Error **errp)
{
    QapiDeallocVisitor *md = qapi_dealloc_visitor_new();
    QmpOutputVisitor *mo = qmp_output_visitor_new();
    Visitor *v;

    v = qmp_output_get_visitor(mo);
    visit_type_CommandInfoList(v, &ret_in, "unused", errp);
    if (!error_is_set(errp)) {
        *ret_out = qmp_output_get_qobject(mo);
    }
    qmp_output_visitor_cleanup(mo);
    v = qapi_dealloc_get_visitor(md);
    visit_type_CommandInfoList(v, &ret_in, "unused", errp);
    qapi_dealloc_visitor_cleanup(md);
}

void qmp_marshal_input_query_commands(QDict *args, QObject **ret, Error **errp)
{
    CommandInfoList * retval = NULL;
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    retval = qmp_query_commands(errp);
    qmp_marshal_output_query_commands(retval, ret, errp);

out:

    return;
}

void qmp_marshal_input_quit(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_quit(errp);

out:

    return;
}

void qmp_marshal_input_stop(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_stop(errp);

out:

    return;
}

void qmp_marshal_input_system_reset(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_system_reset(errp);

out:

    return;
}

void qmp_marshal_input_system_powerdown(QDict *args, QObject **ret, Error **errp)
{
    (void)args;
    if (error_is_set(errp)) {
        goto out;
    }
    qmp_system_powerdown(errp);

out:

    return;
}

static void qmp_init_marshal(void)
{
    qmp_register_command("query-name", qmp_marshal_input_query_name);
    qmp_register_command("query-version", qmp_marshal_input_query_version);
    qmp_register_command("query-kvm", qmp_marshal_input_query_kvm);
    qmp_register_command("query-status", qmp_marshal_input_query_status);
    qmp_register_command("query-uuid", qmp_marshal_input_query_uuid);
    qmp_register_command("query-chardev", qmp_marshal_input_query_chardev);
    qmp_register_command("query-commands", qmp_marshal_input_query_commands);
    qmp_register_command("quit", qmp_marshal_input_quit);
    qmp_register_command("stop", qmp_marshal_input_stop);
    qmp_register_command("system_reset", qmp_marshal_input_system_reset);
    qmp_register_command("system_powerdown", qmp_marshal_input_system_powerdown);
}

qapi_init(qmp_init_marshal);
