/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT MODIFY */

/*
 * schema-defined QAPI function prototypes
 *
 * Copyright IBM, Corp. 2011
 *
 * Authors:
 *  Anthony Liguori   <aliguori@us.ibm.com>
 *
 * This work is licensed under the terms of the GNU LGPL, version 2.1 or later.
 * See the COPYING.LIB file in the top-level directory.
 *
 */

#ifndef QMP_COMMANDS_H
#define QMP_COMMANDS_H

#include "qapi-types.h"
#include "error.h"

NameInfo * qmp_query_name(Error **errp);
VersionInfo * qmp_query_version(Error **errp);
KvmInfo * qmp_query_kvm(Error **errp);
StatusInfo * qmp_query_status(Error **errp);
UuidInfo * qmp_query_uuid(Error **errp);
ChardevInfoList * qmp_query_chardev(Error **errp);
CommandInfoList * qmp_query_commands(Error **errp);
MigrationInfo * qmp_query_migrate(Error **errp);
MouseInfoList * qmp_query_mice(Error **errp);
CpuInfoList * qmp_query_cpus(Error **errp);
BlockInfoList * qmp_query_block(Error **errp);
BlockStatsList * qmp_query_blockstats(Error **errp);
VncInfo * qmp_query_vnc(Error **errp);
SpiceInfo * qmp_query_spice(Error **errp);
BalloonInfo * qmp_query_balloon(Error **errp);
PciInfoList * qmp_query_pci(Error **errp);
void qmp_quit(Error **errp);
void qmp_stop(Error **errp);
void qmp_system_reset(Error **errp);
void qmp_system_powerdown(Error **errp);
void qmp_cpu(int64_t index, Error **errp);



void qmp_marshal_input_quit(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_stop(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_system_reset(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_version(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_commands(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_chardev(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_kvm(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_status(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_name(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_uuid(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_cpu(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_migrate(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_mice(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_cpus(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_block(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_blockstats(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_vnc(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_balloon(QDict* args, QObject** ret, Error** errp);
void qmp_marshal_input_query_pci(QDict* args, QObject** ret, Error** errp);

#endif
